language: julia
dist: trusty
julia:
  - 1.2
notifications:
  email: false
before_install:
  - sudo apt-get install texlive-latex-extra
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'import Pkg; ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build("PyCall")'
  - julia -e 'import Pkg; Pkg.add("Conda"); using Conda; Conda.add("matplotlib")'
  - julia --check-bounds=yes -e 'include("install.jl"); include("runtests.jl")'
